/*
 * This source file was generated by the Gradle 'init' task
 */
package org.llschall.rgbribbon

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertTrue

class RgbRibbonTest {
    @Test
    fun versionIsCorrect() {
        val test = RgbRibbon()
        assertTrue(test.version() == "0.0.2")
    }
}
